inherit_gem:
  rubocop-github:
    - config/default.yml
    - config/rails.yml

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRailsVersion: 4.2
  DisabledByDefault: false
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Lint/Void:
  Exclude:
    - 'features/**/*'
    - 'spec/**/*'
