inherit_from: .rubocop_todo.yml

inherit_gem:
  rubocop-github:
    - config/default_edge.yml
    - config/rails_edge.yml

AllCops:
  TargetRailsVersion: 5.0
  TargetRubyVersion: 2.7
  NewCops: disable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'features/**/*'

# Handle cops not enabled by default
# Should probably be checked on rubocop version upgrades
# Last checked 02/09/21
# Disables cops marked as unsafe in docs

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Performance/AncestorsInclude:
  Enabled: false

Performance/BigDecimalWithNumericArgument:
  Enabled: true

Performance/RedundantSortBlock:
  Enabled: true

Performance/RedundantStringChars:
  Enabled: true

Performance/ReverseFirst:
  Enabled: true

Performance/SortReverse:
  Enabled: true

Performance/Squeeze:
  Enabled: true

Performance/StringInclude:
  Enabled: true

### Override rubcop-github ###

Style/FrozenStringLiteralComment:
  # We aren't upgrading to Ruby 3.0, so this is just noise
  Enabled: false

Metrics/ModuleLength:
  # IME enforcing a module length creates more problems than it solves
  Enabled: false

GitHub/RailsControllerRenderLiteral:
  # Prevents us from dynamically generating layouts
  Enabled: false

GitHub/RailsControllerRenderPathsExist:
  # Doesn't seem to work; can't find templates that exist
  Enabled: false

GitHub/RailsApplicationRecord:
  # Rails/ApplicationRecord does the same thing
  Enabled: false

Lint/Void:
  Exclude:
    - 'features/**/*'
    - 'spec/**/*'

Lint/Debugger:
  Exclude:
    - 'features/step_definitions/debug_steps.rb'

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true

Layout/SpaceInsideBlockBraces:
  Enabled: true

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: true

Layout/ExtraSpacing:
  Enabled: true

Layout/MultilineHashBraceLayout:
  Enabled: true

Layout/SpaceAroundOperators:
  Enabled: true

Naming/PredicateName:
  Exclude:
    - 'spec/**/*'

Security/JSONLoad:
  Enabled: true
  Exclude:
    - 'spec/**/*'

Rails/HttpStatus:
  EnforcedStyle: 'numeric'

Style/Alias:
  Enabled: false

Style/BlockComments:
  Exclude:
    - 'spec/**/*'

Style/ClassAndModuleChildren:
  EnforcedStyle: 'compact'

Style/Documentation:
  Enabled: false

Style/NumericLiterals:
  MinDigits: 6
