name: "Setup"
description: "Installs dependencies"
runs:
  using: "composite"
  steps:
    - name: Install Ruby and gems
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.3"
        bundler-cache: true
    - name: Install npm
      uses: actions/setup-node@v4
      with:
        cache: npm
        cache-dependency-path: 'package-lock.json'
    - name: Install JS dependencies
      shell: bash
      run: npm ci
